[tool.poetry]
name = "decision-tree"
version = "1.1.0"
description = ""
authors = ["Marta <mswolinska@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "^1.22.3"
scikit-learn = ">=1.3.2,<1.4.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
