version: 2.1

orbs:
  python: circleci/python@2.0.3

executors:
  docker-publisher:
    # Define the image tag
    environment:
      IMAGE_TAG: mwolinska/decision-tree:latest
    # Use `docker:stable` as the Docker image for this executor
    docker:
      - image: docker:stable
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_TOKEN

jobs:
  make-new-release:
    docker:
      - image: cimg/python:3.8.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - install-gh-cli
      - run:
          name: Create release
          command: |
            RELEASE_VERSION=$(poetry version --short)
            gh release create $RELEASE_VERSION --generate-notes
  build-docker-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: Build Docker Image
          command: |
            docker build . -f Dockerfile -t decision_tree_test
            docker tag decision_tree_test ${IMAGE_TAG}
            docker push ${IMAGE_TAG}


workflows:
  main:
    jobs:
      - make-new-release:
          filters:
            branches:
              only:
                - master
                - main
          context:
            - GITHUB_CREDS
      - build-docker-image:
          filters:
            branches:
              only:
                - master
                - main
                - add_docker_to_ci
          context:
            - DOCKER_CREDS


commands:
  install-gh-cli:
    description: Install Github CLI
    steps:
      - run:
          name: Get and install gh-cli
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
